settings_play_store_url_market=https://github.com/eduardomillan?tab=packages
settings_play_store_url_https=https://github.com/eduardomillan?tab=packages
settings_hospital_url_https=https://github.com/eduardomillan/ZowiAppReborn
settings_hospital_url_http=http://github.com/eduardomillan/ZowiAppReborn