settings_play_store_url_market=market://details?id=%1$s
settings_play_store_url_https=https://play.google.com/store/apps/details?id=%1$s
settings_hospital_url_https=https://github.com/eduardomillan/ZowiAppReborn
settings_hospital_url_http=http://github.com/eduardomillan/ZowiAppReborn